routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'HomeController@index');

Route::get('/article/{id}', 'ArticleController@index')->name('article');

Route::get('/category/{id}', 'CategoryController@index')->name('category');

Route::get('/tag/{id}', 'TagController@index')->name('tag');

Route::get('/search', 'SearchController@index')->name('search');

Route::get('/page/{alias}', 'PageController@index')->name('page.show');

Route::get('/about', 'PageController@about')->name('about');

Route::get('/rss', 'RssController@index')->name('rss');

Route::namespace('Backend')->prefix('backend')->group(function () {

    Route::get('/login', 'AuthController@showLoginForm')->name('backend.login');

    Route::post('/login', 'AuthController@login');

    Route::get('/logout', 'AuthController@logout');


    Route::group(['middleware' => ['auth', 'reject-null-values']], function(){

        Route::get('/', 'HomeController@index')->name('backend.home');

        Route::post('/upload/image', 'UploadController@image');

        Route::resource('article', 'ArticleController', ['as' => 'backend']);

        Route::resource('category', 'CategoryController', ['as' => 'backend']);

        Route::get('category/set-nav/{id}', ['as' => 'backend.category.set-nav', 'uses' => 'CategoryController@setNavigation']);

        Route::resource('user', 'UserController', ['as' => 'backend']);

        Route::resource('tag', 'TagController', ['as' => 'backend']);

        Route::resource('link', 'LinkController', ['as' => 'backend']);

        Route::resource('navigation', 'NavigationController', ['as' => 'backend']);

        Route::resource('page', 'PageController', ['as' => 'backend']);

        Route::get('system', 'SystemController@index')->name('backend.system.index');

        Route::post('system', 'SystemController@store')->name('backend.system.store');
    });
});

app/Http/Controllers/Backend/ArticleController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Article;
use App\Models\ArticleTag;
use App\Models\Tag;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Auth;
use App\Http\Requests\Backend\Article\CreateRequest;
use App\Http\Requests\Backend\Article\UpdateRequest;

class ArticleController extends Controller
{
    /**
     * @param Request $request
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index(Request $request)
    {
        $articles = tap(Article::latest(), function ($query) use ($request) {
            if ($request->filled('title')) {
                $query->where('title', 'like', "%{$request->title}%");
            }

            if ($request->filled('cate_id')) {
                $query->where('cate_id', $request->cate_id);
            }
        })->with(['user', 'category'])->paginate();

        return view('backend.article.index', compact('articles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.article.create');
    }

    /**
     * @param CreateRequest $request
     * @return $this|\Illuminate\Http\RedirectResponse
     */
    public function store(CreateRequest $request)
    {
        $article = Article::create(array_merge($this->basicFields($request), ['user_id' => Auth::id()]));

        if ($request->filled('tags')) {
            $this->storeArticleTags($article, $request->tags);
        }

        return  redirect()->route('backend.article.index')->with('success', '文章添加成功');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        $article = Article::findOrFail($id);

        return view('backend.article.edit', compact('article'));
    }

    /**
     * @param UpdateRequest $request
     * @param $id
     * @return $this|\Illuminate\Http\RedirectResponse
     */
    public function update(UpdateRequest $request, $id)
    {
        $article = Article::findOrFail($id);

        $article->fill($this->basicFields($request));
        $article->save();

        ArticleTag::where('article_id', $id)->delete();

        if ($request->filled('tags')) {
            $this->storeArticleTags($article, $request->tags);
        }

        return redirect()->route('backend.article.index')->with('success', '文章修改成功');
    }

    /**
     * @param $id
     * @return \Illuminate\Http\JsonResponse
     */
    public function destroy($id)
    {
        return Article::destroy($id) ? response()->json(['status' => 0]) : response()->json(['status' => 1]);
    }

    private function storeArticleTags(Article $article, $tagNames)
    {
        $tagNameList = array_unique(explode(';', trim($tagNames, ';')));
        if (!$tagNameList) {
            return false;
        }

        foreach ($tagNameList as $tagName) {
            $tag = Tag::where('tag_name', $tagName)->first();

            ArticleTag::create([
                'article_id' => $article->id,
                'tag_id' => $tag ? $tag->id : (Tag::create(['tag_name' => $tagName]))->id
            ]);
        }

        return true;
    }

    private function basicFields(Request $request)
    {
        $html = (new \Parsedown())->parse($request->markdown_content);

        return array_merge($request->all([
            'title',
            'keyword',
            'desc',
            'cate_id'
        ]), [
            'content' => $request->get('markdown_content'),
            'html_content' => $html
        ]);
    }
}

app/Http/Controllers/Backend/AuthController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\User;
use Illuminate\Foundation\Auth\AuthenticatesUsers;
use Validator;
use App\Http\Controllers\Controller;

class AuthController extends Controller
{
    /*
    |--------------------------------------------------------------------------
    | Registration & Login Controller
    |--------------------------------------------------------------------------
    |
    | This controller handles the registration of new users, as well as the
    | authentication of existing users. By default, this controller uses
    | a simple trait to add these behaviors. Why don't you explore it?
    |
    */

    use AuthenticatesUsers;

    /**
     * Where to redirect users after login / registration.
     *
     * @var string
     */
    protected $redirectTo = '/backend';


    /**
     * Get a validator for an incoming registration request.
     *
     * @param  array  $data
     * @return \Illuminate\Contracts\Validation\Validator
     */
    protected function validator(array $data)
    {
        return Validator::make($data, [
            'name' => 'required|max:255',
            'email' => 'required|email|max:255|unique:users',
            'password' => 'required|min:6|confirmed',
        ]);
    }

    /**
     * Create a new user instance after a valid registration.
     *
     * @param  array  $data
     * @return User
     */
    protected function create(array $data)
    {
        return User::create([
            'name' => $data['name'],
            'email' => $data['email'],
            'password' => bcrypt($data['password']),
        ]);
    }

    public function showLoginForm()
    {
        return view('backend.login');
    }
}

app/Http/Controllers/Backend/CategoryController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Category;
use App\Models\Navigation;
use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\Category\CreateRequest;
use App\Http\Requests\Backend\Category\UpdateRequest;

class CategoryController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $category = Category::getNestedList('name', null, '&nbsp;&nbsp;&nbsp;&nbsp;');

        return view("backend.category.index", compact('category'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.category.create');
    }

    /**
     * @param CreateRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(CreateRequest $request)
    {
        !$request->cate_id
            ? Category::create(['name' => $request->name])
            : Category::find($request->cate_id)->children()->create(['name' => $request->name]);

        return redirect(route('backend.category.index'))->with('success', '添加成功');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = Category::find($id);

        return view('backend.category.edit', compact('category'));
    }

    /**
     * update
     *
     * @param UpdateRequest $request
     * @param $id
     * @return $this|\Illuminate\Http\RedirectResponse
     */
    public function update(UpdateRequest $request, $id)
    {

        $category = Category::findOrFail($id);

        $category->name = $request->name;
        $category->save();

        if ($request->cate_id != 0 && $category->parent_id != $request->cate_id) {
            $parent = Category::findOrFail($request->cate_id);

            $category->makeChildOf($parent);
        } else {
            $category->makeRoot();
        }

        return redirect(route('backend.category.index'))->with('success', '分类修改成功');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        return Category::destroy($id) ? response()->json(['status' => 0]) : response()->json(['status' => 1]);
    }

    /**
     * @param $id
     * @return $this|\Illuminate\Http\RedirectResponse
     */
    public function setNavigation($id)
    {
        $category = Category::findOrFail($id);

        if (Navigation::query()->where('article_cate_id', $category->id)->count()) {
            return redirect()->back()->withErrors('当前分类已存在导航');
        }

        Navigation::create([
            'article_cate_id' => $category->id,
            'nav_type' => 1,
            'name' => $category->name,
            'url' => route('category', ['id' => $category->id]),
            'sequence' => 0
        ]);

        return redirect()->back()->with('success', '设置成功');
    }
}

app/Http/Controllers/Backend/HomeController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Auth;

class HomeController extends Controller
{
    public function index()
    {
        return view('backend.home');
    }
}

app/Http/Controllers/Backend/LinkController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\Link\CreateRequest;
use App\Http\Requests\Backend\Link\UpdateRequest;
use App\Models\Link;

class LinkController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $links = Link::all();

        return view('backend.link.index', compact('links'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.link.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CreateRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(CreateRequest $request)
    {
        Link::create($request->all());

        return redirect()->route('backend.link.index')->with('success', '友情链接添加成功');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $link = Link::find($id);

        return view('backend.link.edit', compact('link'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateRequest $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UpdateRequest $request, $id)
    {
        $link = Link::findOrFail($id);

        $link->fill($request->all());
        $link->save();

        return redirect()->route('backend.link.index')->with('success', '友情链接修改成功');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        return Link::destroy($id) ? response()->json(['status' => 0]) : response()->json(['status' => 0]);
    }
}

app/Http/Controllers/Backend/NavigationController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Navigation;
use App\Http\Controllers\Controller;
use App\Http\Requests\Backend\Navigation\CreateRequest;
use App\Http\Requests\Backend\Navigation\UpdateRequest;

class NavigationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $navigations = Navigation::query()->with([
            'category'
        ])->orderBy('sequence', 'desc')->get();

        return view('backend.navigation.index', compact('navigations'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.navigation.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param CreateRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(CreateRequest $request)
    {
        Navigation::create($request->all());

        return redirect()->route('backend.navigation.index')->with('success', '导航添加成功');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $navigation = Navigation::findOrFail($id);

        return view('backend.navigation.edit', compact('navigation'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param UpdateRequest $request
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(UpdateRequest $request, $id)
    {
        $navigation = Navigation::findOrFail($id);

        $navigation->fill($request->all());
        $navigation->save();

        return redirect()->route('backend.navigation.index')->with('success', '导航修改成功');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        return Navigation::destroy($id) ? response()->json(['status' => 0]) : response()->json(['status' => 1]);
    }
}

app/Http/Controllers/Backend/SystemController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\System;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SystemController extends Controller
{
    public function index()
    {
        $system = System::optionList();

        return view('backend.system.index', compact('system'));
    }

    public function store(Request $request)
    {
        foreach ($request->all() as $key => $value) {
            if (in_array($key, config('blog.system_key'))) {
                System::updateOrCreate(['key' => $key], ['value' => $value]);
            }
        }

        return redirect()->back()->with('success', '操作成功');
    }
}

app/Http/Controllers/Backend/UploadController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Storage;

class UploadController extends  Controller
{
    public function image(Request $request)
    {
        if ($request->hasFile('file')
            && $request->file('file')->isValid()
            && in_array($request->file->extension(), ["png", "jpg", "jpeg", "gif"])
        ) {
            $path = $request->file->store(date('Ymd'), config('blog.disk'));

            $url = Storage::disk(config('blog.disk'))->url($path);

            return response()->json(['filename' => $url]);
        }
    }
}

resources/views/backend/user/create.blade.php
@extends('layouts.backend')

@section('title', '博客用户添加')

@section('header')
    <h1>
        博客用户添加
    </h1>
@endsection

@section('content')
    <div class="row">
        <div class="col-xs-12">
            @include('backend.alert.warning')
            <div class="box box-solid">
                <form role="form" method="post" enctype="multipart/form-data" action="{{ url('backend/user') }}" id="user-form" >
                    <div class="box-body">
                        <div class="form-group">
                            <label for="user_pic">头像</label>
                            <div class="row">
                                <div class='col-md-6'>
                                    <input type="file" name="user_pic" id="user_pic" accept="image/png,image/gif,image/jpeg">
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="name">名字</label>
                            <div class="row">
                                <div class='col-md-6'>
                                    <input type='text' class='form-control' name="name" id='name' placeholder='请输入名字'>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="email">登录邮箱</label>
                            <div class="row">
                                <div class='col-md-6'>
                                    <input type="text" class='form-control' name="email" id="email" placeholder="请输入唯一的邮箱">
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="password">登录密码</label>
                            <div class="row">
                                <div class='col-md-6'>
                                    <input type="password" class='form-control' name="password" id="password" placeholder="请输入大于等于8位的密码">
                                </div>
                            </div>
                        </div>

                    </div>

                    {{ csrf_field() }}


                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">确定</button>
                        <button type="button" class="btn btn-warning" id="reset-btn">重置</button>
                    </div>
                </form>
            </div>
            <!-- /.box -->
        </div>
    </div>
@endsection

resources/views/backend/user/edit.blade.php
@extends('layouts.backend')

@section('title', '博客用户修改')

@section('header')
    <h1>
        博客用户修改
    </h1>
@endsection

@section('content')
    <div class="row">
        <div class="col-xs-12">
            @include('backend.alert.warning')
            <div class="box box-solid">
                <form role="form" method="post" enctype="multipart/form-data" action="{{ route('backend.user.update', ['id' => $user->id]) }}" id="edit-user-form">
                    <div class="box-body">
                        <div class="form-group">
                            <label for="user_pic">头像</label>
                            <div class="row">
                                <div class='col-md-3'>
                                    <input type="file" name="user_pic" id="user_pic" accept="image/png,image/gif,image/jpeg" >
                                </div>
                                <div class='col-md-6'>
                                    <img src="{{ $user->user_pic }}" class="img-circle" style="width:80px;height:auto;">
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="name">名字</label>
                            <div class="row">
                                <div class='col-md-6'>
                                    <input type='text' value="{{ $user->name }}" class='form-control' name="name" id='name' placeholder='请输入名字'>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="email">登录邮箱</label>
                            <div class="row">
                                <div class='col-md-6'>
                                    <input type="text" value="{{ $user->email }}" class='form-control' name="email" id="email" placeholder="请输入唯一的邮箱">
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="password">登录密码</label>
                            <div class="row">
                                <div class='col-md-6'>
                                    <input type="password" class='form-control' name="password" id="password" placeholder="请输入大于等于8位的密码">
                                </div>
                            </div>
                        </div>

                    </div>

                    {{ csrf_field() }}
                    {{ method_field('PUT') }}


                    <div class="box-footer">
                        <button type="submit" class="btn btn-primary">确定</button>
                        <button type="button" class="btn btn-warning" id="reset-btn">重置</button>
                    </div>
                </form>
            </div>
            <!-- /.box -->
        </div>
    </div>
@endsection

resources/views/backend/user/index.blade.php
@extends('layouts.backend')

@section('title', '用户列表')

@section('header')
    <h1>
        用户列表
    </h1>
@endsection

@section('content')
    <div class="row">
        <div class="col-xs-12">
            @include('backend.alert.success')
            <div class="box box-solid">
                <!-- /.box-header -->
                <div class="box-header">
                    <div class="pull-right">
                        <div class="btn-group">
                            <a href="{{ route('backend.user.create') }}" class="btn btn-white tooltips"
                               data-toggle="tooltip" data-original-title="新增"><i
                                        class="glyphicon glyphicon-plus"></i></a>
                        </div>
                    </div><!-- pull-right -->
                </div>
                <div class="box-body table-responsive no-padding ">
                    <table class="table table-hover">
                        <tr>
                            <th>序号</th>
                            <th>头像</th>
                            <th>名字</th>
                            <th>邮箱</th>
                            <th>操作</th>
                        </tr>
                        @if ($users)
                            <?php $line = 1  ?>
                            @foreach($users as $u)
                                <tr>
                                    <td>{{ $line }}</td>
                                    <td>
                                        <img src="{{  $u['user_pic'] }}" class="img-circle" style="width:30px;height:auto;">
                                    </td>
                                    <td>{{ $u['name'] }}</td>
                                    <td>{{ $u['email'] }}</td>
                                    <td>
                                        <a href='{{ route("backend.user.edit", ["id" => $u['id']]) }}' class='btn btn-info btn-xs'>
                                            <i class="fa fa-pencil"></i> 修改</a>
                                        <a data-href='{{ route("backend.user.destroy", ["id" => $u['id']]) }}'
                                           class='btn btn-danger btn-xs user-delete'><i class="fa fa-trash-o"></i> 删除</a>
                                    </td>
                                </tr>
                                <?php $line++ ?>
                            @endforeach
                        @endif
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
    </div>
@endsection

@section('javascript')
    <script>
        $(function() {
            $(".user-delete").click(function(){
                var url = $(this).attr('data-href');
                Moell.ajax.delete(url);
            });
        });
    </script>
@endsection